# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3cac5abf0fed7fe6772954b268bb3d5ce1a67018f726c2a839505d90617d51381beee18a43d4c781d6979d0c5044366fa8d95a8ddb05addd86afb4a9215caee

test:
  secret_key_base: 030cbb546e1b9c86c48c3491c2cfe232d07afe75279f280ec67aefa30cf27714006ca9a6f6da8114a637da204957967540f14c8f8090e5c8e741b0dbfd98b966

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
